### ISSUE TITLE
Karma chrashes with: Fatal error: Wrong length [0.13.16 regression]

### ISSUE THREAD

**Issue by egoroof** [karma-runner/karma#1768] opened 2015-12-25 02:32 UTC
I've just updated from 0.13.15 where everything was fine to 0.13.16 and run tests. Karma has crashed with IE runner (with chrome and firefox there are no problems):

```
> karma start --single-run

25 12 2015 10:42:06.907:DEBUG [config]: autoWatch set to false, because of singleRun
25 12 2015 10:42:06.914:DEBUG [plugin]: Loading karma-* from E:\Dropbox\repo\browser-id3-writer\node_modules
25 12 2015 10:42:06.918:DEBUG [plugin]: Loading plugin E:\Dropbox\repo\browser-id3-writer\node_modules/karma-chai.
25 12 2015 10:42:06.920:DEBUG [plugin]: Loading plugin E:\Dropbox\repo\browser-id3-writer\node_modules/karma-chrome-launcher.
25 12 2015 10:42:06.931:DEBUG [plugin]: Loading plugin E:\Dropbox\repo\browser-id3-writer\node_modules/karma-coverage.
25 12 2015 10:42:07.270:DEBUG [plugin]: Loading plugin E:\Dropbox\repo\browser-id3-writer\node_modules/karma-firefox-launcher.
25 12 2015 10:42:07.274:DEBUG [plugin]: Loading plugin E:\Dropbox\repo\browser-id3-writer\node_modules/karma-ie-launcher.
25 12 2015 10:42:07.321:DEBUG [plugin]: Loading plugin E:\Dropbox\repo\browser-id3-writer\node_modules/karma-mocha.
25 12 2015 10:42:07.399:DEBUG [preprocessor.coverage]: Processing "E:/Dropbox/repo/browser-id3-writer/src/browser-id3-writer.js".
25 12 2015 10:42:07.508:INFO [karma]: Karma v0.13.16 server started at http://localhost:9876/
25 12 2015 10:42:07.517:INFO [launcher]: Starting browser IE
25 12 2015 10:42:07.518:DEBUG [temp-dir]: Creating temp dir at C:\Users\12C2~1\AppData\Local\Temp\karma-54524961
25 12 2015 10:42:07.523:DEBUG [launcher]: C:\Program Files\Internet Explorer\iexplore.exe http://localhost:9876/?id=54524961
25 12 2015 10:42:07.858:DEBUG [web-server]: serving: E:\Dropbox\repo\browser-id3-writer\node_modules\karma\static/client.html
25 12 2015 10:42:07.890:DEBUG [web-server]: serving: E:\Dropbox\repo\browser-id3-writer\node_modules\karma\static/karma.js
25 12 2015 10:42:08.021:DEBUG [karma]: A browser has connected on socket SBAFIfzlxXRz6LWaAAAA
25 12 2015 10:42:08.035:DEBUG [web-server]: upgrade /socket.io/?EIO=3&transport=websocket&sid=SBAFIfzlxXRz6LWaAAAA
25 12 2015 10:42:08.082:INFO [IE 11.0.0 (Windows 10 0.0.0)]: Connected on socket SBAFIfzlxXRz6LWaAAAA with id 54524961
25 12 2015 10:42:08.085:DEBUG [launcher]: IE (id 54524961) captured in 0.576 secs
25 12 2015 10:42:08.095:DEBUG [web-server]: serving: E:\Dropbox\repo\browser-id3-writer\node_modules\karma\static/context.html
IE 11.0.0 (Windows 10 0.0.0): Executed 1 of 1 SUCCESS (0.018 secs / 0 secs)
25 12 2015 10:42:08.230:DEBUG [karma]: Run complete, exiting.
25 12 2015 10:42:08.236:DEBUG [launcher]: Disconnecting all browsers
25 12 2015 10:42:08.239:ERROR [karma]: [RangeError: Wrong length!]
RangeError: Wrong length!
    at RangeError (native)
    at strictToLength (E:\Dropbox\repo\browser-id3-writer\node_modules\core-js\modules\_typed-array.js:94:36)
    at E:\Dropbox\repo\browser-id3-writer\node_modules\core-js\modules\_typed-array.js:404:44
    at new Uint8Array (E:\Dropbox\repo\browser-id3-writer\node_modules\core-js\modules\es6.typed.uint8-array.js:3:12)
    at allocate (buffer.js:98:17)
    at new Buffer (buffer.js:49:12)
    at BufferPool.reset (E:\Dropbox\repo\browser-id3-writer\node_modules\ws\lib\BufferPool.js:57:26)
    at Receiver.endPacket (E:\Dropbox\repo\browser-id3-writer\node_modules\ws\lib\Receiver.js:247:68)
    at Receiver.opcodes.1.finish (E:\Dropbox\repo\browser-id3-writer\node_modules\ws\lib\Receiver.js:483:12)
    at Receiver.expectHandler (E:\Dropbox\repo\browser-id3-writer\node_modules\ws\lib\Receiver.js:451:33)
    at Receiver.add (E:\Dropbox\repo\browser-id3-writer\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (E:\Dropbox\repo\browser-id3-writer\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
25 12 2015 10:42:08.253:DEBUG [launcher]: Disconnecting all browsers
25 12 2015 10:42:08.258:DEBUG [coverage]: Writing coverage to E:/Dropbox/repo/browser-id3-writer/coverage
25 12 2015 10:42:08.457:DEBUG [launcher]: Killed extra IE process 3724
25 12 2015 10:42:08.457:DEBUG [launcher]: Process IE exited with code 0
25 12 2015 10:42:08.458:DEBUG [temp-dir]: Cleaning temp dir C:\Users\12C2~1\AppData\Local\Temp\karma-54524961
25 12 2015 10:42:08.462:DEBUG [launcher]: Finished all browsers

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! browser-id3-writer@0.0.0-semantically-released test: `karma start --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browser-id3-writer@0.0.0-semantically-released test script 'karma start --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the browser-id3-writer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start --single-run
npm ERR! You can get their info via:
npm ERR!     npm owner ls browser-id3-writer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Dropbox\repo\browser-id3-writer\npm-debug.log
```

**Comment by mistadikay** [comment] 2015-12-25 03:38
the same with Firefox on Mac OS:

```
25 12 2015 10:38:15.898:ERROR [karma]: [RangeError: Wrong length!]
RangeError: Wrong length!
    at RangeError (native)
    at strictToLength (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/karma/node_modules/core-js/modules/_typed-array.js:94:36)
    at /Users/lazhcm10348/Projects/lazada/page-manager/node_modules/karma/node_modules/core-js/modules/_typed-array.js:404:44
    at new Uint8Array (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/karma/node_modules/core-js/modules/es6.typed.uint8-array.js:3:12)
    at allocate (buffer.js:98:17)
    at new Buffer (buffer.js:49:12)
    at BufferPool.reset (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/ws/lib/BufferPool.js:57:26)
    at Receiver.endPacket (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/ws/lib/Receiver.js:247:68)
    at Receiver.opcodes.1.finish (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/ws/lib/Receiver.js:483:12)
    at Receiver.expectHandler (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/ws/lib/Receiver.js:451:33)
    at Receiver.add (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/Users/lazhcm10348/Projects/lazada/page-manager/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
25 12 2015 10:38:15.900:DEBUG [launcher]: Disconnecting all browsers
25 12 2015 10:38:16.033:DEBUG [launcher]: Process Firefox exited with code 0
25 12 2015 10:38:16.033:DEBUG [temp-dir]: Cleaning temp dir /var/folders/81/kv16vyjs3r9gyfc1dp6qhtjc0000gn/T/karma-18684574
25 12 2015 10:38:16.057:DEBUG [launcher]: Finished all browsers

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/lazhcm10348/.nvm/versions/node/v5.3.0/bin/node" "/Users/lazhcm10348/.nvm/versions/node/v5.3.0/bin/npm" "run" "task" "tdd"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! page-manager@2.9.1 task: `babel-node node_modules/.bin/start tasks/ "tdd"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the page-manager@2.9.1 task script 'babel-node node_modules/.bin/start tasks/ "tdd"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the page-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node node_modules/.bin/start tasks/ "tdd"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs page-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls page-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lazhcm10348/Projects/lazada/page-manager/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/lazhcm10348/.nvm/versions/node/v5.3.0/bin/node" "/Users/lazhcm10348/.nvm/versions/node/v5.3.0/bin/npm" "run" "tdd"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! page-manager@2.9.1 tdd: `npm run task tdd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the page-manager@2.9.1 tdd script 'npm run task tdd'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the page-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run task tdd
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs page-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls page-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lazhcm10348/Projects/lazada/page-manager/npm-debug.log
```

**Comment by mistadikay** [comment] 2015-12-25 03:41
It's probably because of upgrading `core-js` to `2.0.0`

**Comment by zloirock** [comment] 2015-12-25 05:12
`core-js` 2.0 converts typed arrays for conformity with ES6. By ES6, you will have this error, for example, on `new Uint8Array(1.5)`.

**Comment by ruslansagitov** [comment] 2015-12-25 13:22
In Firefox 31.0.0 on Linux (Travis CI) also.

**Comment by falsandtru** [comment] 2015-12-25 14:42
I got a same error with Karma 0.13.16 .

**Comment by zloirock** [comment] 2015-12-25 15:28
@falsandtru see my comment above. This is *fixed* by #1765 because [by ES6 `RangeError` should be thrown here](https://github.com/tc39/ecma262/issues/265) :) Missed error here - [V8 bug](https://code.google.com/p/v8/issues/detail?id=4552).

**Comment by falsandtru** [comment] 2015-12-25 15:40
@zloirock thanks for your response. Excuse me, how can we solve this problem? Won't fix?

**Comment by zloirock** [comment] 2015-12-25 15:51
@falsandtru rather it's not `core-js` issue.
> Looks like the problem in `ws` module in `BufferPool` (`Buffer` inherited from `Uint8Array`).

I can't reproduce it. Most likely to `Buffer` constructor (-> `Uint8Array`) passed an invalid argument. [See this part of spec](http://tc39.github.io/ecma262/#sec-arraybuffer-length).

**Comment by falsandtru** [comment] 2015-12-25 17:04
> I can't reproduce it.

It error seems caused by coverage processing.

```js
      reporters: ['dots', 'coverage'],
      preprocessors: {
        'dist/*.js': ['coverage']
      },
```

It error also caused on Firefox and Chrome. Not only IE.

Windows7 x64 latest
Chrome 47.0.2526
Firefox 43.0.0

**Comment by Dignifiedquire** [comment] 2015-12-25 18:36
@falsandtru do you have a repo I can test with?

**Comment by DevVersion** [comment] 2015-12-25 18:51
I got the same problem, while contributing to Angular Material, I also removed my tests (so it isn't a fault from the specs) My previous contributions yesterday worked perfectly, so it seem's to be the Commit https://github.com/karma-runner/karma/commit/6c9e2b17bdc4fbaec8e05fbf534c9a4ca4e20194)

**Comment by egoroof** [comment] 2015-12-26 02:37
@Dignifiedquire you can test my repo (if you have windows): https://github.com/egoroof/browser-id3-writer

```
npm install browser-id3-writer
npm run test
```

**Comment by falsandtru** [comment] 2015-12-26 08:41
@egoroof yeah,
@Dignifiedquire simple repro:

https://github.com/falsandtru/karma-1768

**Comment by thangngoc89** [comment] 2015-12-26 23:58
I got the same error too.

Crash only happens when I enable coverage

**Comment by Dignifiedquire** [comment] 2015-12-27 11:07
Filed a PR to `ws` so this issue gets fixed at the source: https://github.com/websockets/ws/pull/645. Depending on the speed of this getting into a release I will create a release with downgraded core-js in the next days. 
Thanks for the help everyone.

**Comment by egoroof** [comment] 2015-12-27 11:11
@Dignifiedquire thanks!

**Comment by diwu1989** [comment] 2015-12-28 21:25
Also seeing problems.... have to revert to older version of karma unfortunately

**Comment by DevVersion** [comment] 2015-12-28 21:26
@Dignifiedquire's PR is already merged, so now we need to wait for a quick release.

**Comment by SpainTrain** [comment] 2015-12-30 18:45
Is it possible to get the issue title updated to reflect the updated info about the bug?  Was not clear what this was when viewing the issue list (I had to find it via SO).  Thanks :heart:

**Comment by dtothefp** [comment] 2015-12-30 19:42
@Dignifiedquire I can confirm that I encounter this issue only when running code coverage reporting after upgrading to `0.13.6` with `core-js v2.0.0`. Same error stack trace as shown above in the original issue.

**Comment by egoroof** [comment] 2015-12-31 03:09
@SpainTrain It's done.

**Comment by Dignifiedquire** [comment] 2015-12-31 12:13
No we need engine.io to upgrade ws: https://github.com/socketio/engine.io/issues/373 and after that socket.io to upgrade engine.io...

**Comment by zloirock** [comment] 2015-12-31 12:42
Maybe makes sense temporary remove this fix from `core-js`, but anyway it will be broken after fixing this bug in V8...

**Comment by emilioplatzer** [comment] 2016-01-03 19:38
+1. I have the same problem https://travis-ci.org/codenautas/tedede/jobs/99987514

**Comment by zloirock** [comment] 2016-01-03 23:18
Because it creates too many problems for you, I have temporarily removed `length` validation from `Uint8Array` in `core-js` `2.0.2`, so you can just update `core-js`. I will return it when this V8 bug and bugs in all required packages will be fixed.

**Comment by Dignifiedquire** [comment] 2016-01-03 23:30
@zloirock thanks a lot! and sorry for all the issues, I will push a release with that version in the morning.

**Comment by Dignifiedquire** [comment] 2016-01-04 15:33
Should be fixed in [`0.13.7`] (https://github.com/karma-runner/karma/releases/tag/v0.13.17)

**Closed by Dignifiedquire** 2016-01-04 15:33 UTC
Labels: priority: high, type: bug-upstream

**Comment by egoroof** [comment] 2016-01-04 16:29
@Dignifiedquire thanks! It is fixed.

**Comment by zzo** [comment] 2016-01-04 19:16
Thanks @Dignifiedquire for the quick turnaround!
