### ISSUE TITLE
"files" globs match partial filenames

### ISSUE THREAD

**Issue by corence** [karma-runner/karma#2775] opened 2017-07-14 03:04 UTC
### Expected behaviour
```
                    {pattern: 'dist/**/*.js', included: false}
```
This pattern should match `dist/abc/def/filename.js` but should *not* match `dist/abc/def/filename.js.map`

### Actual behaviour
It matches both files

### Environment Details

- Karma version (output of `karma --version`): 0.12.31
- Relevant part of your `karma.config.js` file:
```
grunt.config('karma', {
    options: {
        files: [
            {pattern: 'dist/**/*.js', included: false}
        ]
    }
}
```

### Steps to reproduce the behaviour

1. in karma configuration file, set options.files to `[{pattern: 'dist/**/*.js'}]`
2. create a file called `dist/abc/filename.js.map` and another one called `dist/abc/filename2.js` 
3. run the tests and watch to see which files are included

### Workaround
if i append `!(.)` to the pattern, this works
```
                    {pattern: 'dist/**/*.js!(.)', included: false}
```
This filters out `dist/abc/def/filename.js.map` (which is good enough for my use-case)

But it doesn't seem to be a complete solution

**Comment by chrahunt** [comment] 2017-07-19 22:03
I have tried unsuccessfully to reproduce your issue. Can you for my example [here](https://github.com/chrahunt/karma-repro-2775) and try to make it fail in the way you're describing?

**Comment by EzraBrooks** [comment] 2017-11-25 01:22
Closing this issue since @chrahunt was unable to reproduce. Please re-open if you can provide an example reflecting the issue you experienced.

**Closed by EzraBrooks** 2017-11-25 01:22 UTC
Labels: cannot-reproduce
