### ISSUE TITLE
How can i make my karma fail the tests if the transpilation step fails?

### ISSUE THREAD

**Issue by bertolo1988** [karma-runner/karma#2802] opened 2017-08-08 14:50 UTC
Hello,

I introduced an error in my code and my karma tests still pass even though the transpilation step is not successful.

Here is my output:

```bash
tbertolo@tbertolo-Latitude-5580:~/code/slickss/driver-app$ npm run test

> driverapp@0.0.1 test /home/tbertolo/code/slickss/driver-app
> karma start ./test-config/karma.conf.js --single-run


webpack: Compiled successfully.
webpack: Compiling...
ts-loader: Using typescript@2.3.4 and /home/tbertolo/code/slickss/driver-app/tsconfig.json

ERROR in /home/tbertolo/code/slickss/driver-app/src/app/main.ts
(5,26): error TS2339: Property 'bootstrapModue' does not exist on type 'PlatformRef'.
webpack: Failed to compile.
08 08 2017 15:42:43.359:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
08 08 2017 15:42:43.361:INFO [launcher]: Launching browser Chrome with unlimited concurrency
08 08 2017 15:42:43.365:INFO [launcher]: Starting browser Chrome
08 08 2017 15:42:44.953:INFO [Chrome 60.0.3112 (Linux 0.0.0)]: Connected on socket M5mX0gXyw8gbpxhxAAAA with id 84710586
..
Chrome 60.0.3112 (Linux 0.0.0): Executed 2 of 2 SUCCESS (0.079 secs / 0.066 secs)

```

Is it possible to abort the execution with a failure (travis.ci must fail the test) if such thing happens?

**Comment by EzraBrooks** [comment] 2017-12-02 02:25
This appears to be a duplicate of #2800.

**Closed by EzraBrooks** 2017-12-02 02:25 UTC
