### ISSUE TITLE
Karma run clientArgs persist between runs

### ISSUE THREAD

**Issue by dcosson** [karma-runner/karma#2323] opened 2016-08-18 17:02 UTC
### Expected behavior

I have a karma already launched with a browser attached, `karma start --run-once=false`. Using `karma-jasmine` adapter.

I run:

```
karma run -- --grep=foo
karma run
```

I expect the first one to run just matching "foo" and the second to run all the tests.
### Actual behavior

The second one just runs the "grep=foo" tests.

I went in and added logging in the entrypoints of the karma-jasmine adapter, and I see that `window.__karma__.config` still has `args: ['--grep=foo']` on the second run.

Since it doesn't look like karma-jasmine ever sets this value, this seems like a bug in karma itself rather than in the framework adapter. Karma is not clearing `window.__karma__` between runs.
### Enviroment Details
- Karma version (output of `karma --version`): 1.2.0
- Relevant part of your `karma.config.js` file N/A
### Steps to reproduce the behaviour

Described above

**Comment by EzraBrooks** [comment] 2017-12-05 17:05
#2819 is a duplicate of this issue, but it has more details on the issue so I'm going to close this one instead. Thanks for the report!

**Closed by EzraBrooks** 2017-12-05 17:05 UTC
