### ISSUE TITLE
Wrong log while watching when test is focused

### ISSUE THREAD

**Issue by chaabenMohamed** [karma-runner/karma#2587] opened 2017-02-28 16:43 UTC
### Issue
When running karma in watch mode, the log is correct, after focusing one test (we tell karma to run only that test and not all the tests), the log displays always the result of running all the tests. However, after verifying the execution in the browser, only one test have been executed.
This issue does't exist in v0.13.22, it only appears starting from v1.0.0.

### Expected behaviour
Log: 

> Executed 1 of 62 (skipped 61) SUCCESS

### Actual behaviour
 Log: 

> Executed 62 of 62 SUCCESS

### Environment Details

- Karma version (output of `karma --version`): v1.0.0
karma.config.js:
```
'use strict';

module.exports = function (config) {
  config.set({
    plugins: [
      'karma-jasmine',
      'karma-chrome-launcher',
      'karma-firefox-launcher',
      'karma-ng-html2js-preprocessor',
      'karma-coverage',
      'karma-junit-reporter',
    ],
    autoWatch: true,
    basePath: '',
    frameworks: [
      'jasmine',
    ],
    reporters: ['progress', 'junit'],

    files: [
      'app/components/**/*.html',
      'app/components/**/*_test.compiled.js',

      'test-utils/custom-matchers/**/*.compiled.js',
      {
        pattern: 'app/components/**/testdata/*.json',
        included: false,
      }
    ],

    // list of files / patterns to exclude
    exclude: [
      'app/tpl/app.js',
    ],
    port: 8080,
    browsers: [
      'Firefox',
      'Chrome',
    ],
    singleRun: false,
    colors: true,
    logLevel: config.LOG_INFO,
    ngHtml2JsPreprocessor: {
      stripPrefix: 'app/',
      moduleName: 'universignNgWebApp.templates',
    },
    preprocessors: {
      'app/components/**/*.html': ['ng-html2js'],
    },
    junitReporter: {
      outputDir: 'unit-tests-reports',
      outputFile: 'report.xml',
    },
  });

  if (!config.skipCoverage) {
    // preprocess files for coverage
    config.preprocessors['app/components/**/!(*_test.compiled).js'] =
      ['coverage'];

    // define coverage reporter
    config.reporters.push('coverage');

    // configure coverage reporter
    config.coverageReporter = {
      dir: 'coverage',
      reporters: [
        { type: 'html', subdir: 'report-html' },
        { type: 'lcov', subdir: 'report-lcov' },
      ],
    };
  }
};
```

### Steps to reproduce the behaviour
1. Run unit tests
2. Check the log
3. Focus one test
4. Check the log

**Comment by maksimr** [comment] 2017-03-12 01:28
@chaabenMohamed could you add `karma.config` to the description or create a stub project which reproduces the problem because I can't reproduce the problem using `karma@1.5.0`,`karma-jasmine@1.1.0` and `jasmine-core@2.5.2`

Thanks

**Comment by chaabenMohamed** [comment] 2017-03-22 08:39
@maksimr karma.config has bin added in old comment.

**Comment by maksimr** [comment] 2017-03-22 08:44
@chaabenMohamed try remove **junit** reporter

**Comment by chaabenMohamed** [comment] 2017-03-22 09:54
I removed junit reporter but I still have the same problem

**Comment by maksimr** [comment] 2017-03-22 10:05
@chaabenMohamed thanks

Could you create project which reproduces this problem then I can investigate this

**Comment by maksimr** [comment] 2017-03-25 08:01
@chaabenMohamed do you run karma without code coverage?

**Comment by chaabenMohamed** [comment] 2017-03-28 08:22
I have runed karma without code coverage coverage but it still have the same problem.

**Comment by maksimr** [comment] 2017-03-28 08:31
@chaabenMohamed Could you create a project with the problem which I can download and run on my local machine?

**Comment by devoto13** [comment] 2020-05-19 23:12
Looks like this has been fixed by https://github.com/karma-runner/karma-jasmine/pull/192, but hard to say for sure without having a minimal reproduction as requested above. I'm going to close this one, but feel free to open a new issue including minimal reproduction if you still experience this problem.

**Closed by devoto13** 2020-05-19 23:12 UTC
Labels: needs: feedback-from-author
