### ISSUE TITLE
IE6 freeze on sauce Labs

### ISSUE THREAD

**Issue by SergioCrisostomo** [karma-runner/karma#983] opened 2014-03-24 18:10 UTC
Hi all!

I have been trying to test my javascript with Grunt/Karma/Jasmine on SauceLabs and I get a recurrent error: `internet explorer 6 (Windows XP) on SauceLabs have not captured in 120000 ms, killing.`

Is this a know issue? is there a "right way to do this?"

All other IE work on my tests, just IE6 doesn't. I Can see on SauceLabs "Karma is running" but nothing more happens.

Had issue open at  [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher/issues/24), but seems the problem might be Karma. 

I know IE6 is almost dead, but still would like to know why this hangs.

**Comment by riggerthegeek** [comment] 2015-08-08 07:47
Karma v0.13 has removed `json-polling` from it's list of [transports](http://karma-runner.github.io/0.13/config/configuration-file.html) and replaced with `polling`.  However, no matter what I try, I can't get this to work in v0.13.

It seems that, if you want IE6 support, you need to use Karma v0.12.  This also seems to be the case with IE7 too.

**Comment by Dignifiedquire** [comment] 2015-08-10 08:08
@riggerthegeek you should be able to add any transport that socket.io supports through the `transports` option, does that not work for you?

**Comment by riggerthegeek** [comment] 2015-08-10 08:21
@Dignifiedquire Yeah, it's working as expected.  It's just that in v0.13, `jsonp-polling` has been removed and replaced with simply `polling`.  This doesn't seem to work in the same way (my IE6/7 tests timeout).

Take a look at the [v0.13](http://karma-runner.github.io/0.13/config/configuration-file.html) docs against the [v0.12](http://karma-runner.github.io/0.12/config/configuration-file.html) docs

**Comment by Dignifiedquire** [comment] 2015-08-10 12:32
Okay, so the transport `jsonp-polling` has been removed from socket.io in version 1.0. But it should be possible to force it to jsonp instead of xhr polling with the option `forceJSONP` https://github.com/socketio/socket.io-client/blob/e76a671b764ad3314ee98b2c6fe2cc83b0ebc8fa/socket.io.js#L2446-L2450 
could you try adding this to https://github.com/karma-runner/karma/blob/master/lib/server.js#L33 and see if that fixes the issue for you?

**Comment by riggerthegeek** [comment] 2015-08-10 15:17
It looks like it should work, but I doesn't.  I added the `forceJSONP` stuff in the [server.js](https://github.com/karma-runner/karma/blob/master/lib/server.js#L33) but it doesn't work.  What I have noticed that it doesn't appear that the section in [socket.io-client](https://github.com/socketio/socket.io-client/blob/e76a671b764ad3314ee98b2c6fe2cc83b0ebc8fa/socket.io.js#L2446-L2450) doesn't appear to get called at all.

I've had a brief look whilst at work, but it's not as easy as we'd first hoped.  I'll see fork and see if I can fix it, but might not be immediately

**Comment by riggerthegeek** [comment] 2015-08-10 15:17
It looks like it should work, but I doesn't.  I added the `forceJSONP`
stuff in the [server.js](
https://github.com/karma-runner/karma/blob/master/lib/server.js#L33) but it
doesn't work.  What I have noticed that it doesn't appear that the section
in [socket.io-client](
https://github.com/socketio/socket.io-client/blob/e76a671b764ad3314ee98b2c6fe2cc83b0ebc8fa/socket.io.js#L2446-L2450)
doesn't appear to get called at all.

I've had a brief look whilst at work, but it's not as easy as we'd first
hoped.  I'll see fork and see if I can fix it, but might not be immediately

On 10 August 2015 at 13:32, Friedel Ziegelmayer <notifications@github.com>
wrote:

> Okay, so the transport jsonp-polling has been removed from socket.io in
> version 1.0. But it should be possible to force it to jsonp instead of xhr
> polling with the option forceJSONP
> https://github.com/socketio/socket.io-client/blob/e76a671b764ad3314ee98b2c6fe2cc83b0ebc8fa/socket.io.js#L2446-L2450
> could you try adding this to
> https://github.com/karma-runner/karma/blob/master/lib/server.js#L33 and
> see if that fixes the issue for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karma-runner/karma/issues/983#issuecomment-129427401>.
>

-- 



*Tel:* 01905 571175
*Mob: *07736 650058
*Web:* www.simonemms.com
*Skype:* RiggerTheGeek


NOTE: The information contained in this email is intended for the named 
recipients only, it may be privileged and confidential. If you are not the 
intended recipient, you must not copy distribute or take any action in 
reliance upon it. No warranties or assurances are made in relation to the 
safety and content of this email and any attachments. No liability is 
accepted for any consequences arising from it.

**Comment by Krinkle** [comment] 2015-08-25 00:10
Noticed the same regression at Wikimedia when trying to upgrade to Karma v0.13.

```
25 08 2015 01:36:11.190:INFO [karma]: Karma v0.13.3 server started at http://localhost:9876/
25 08 2015 01:36:11.191:INFO [launcher]: Starting browser safari 6 on SauceLabs
25 08 2015 01:36:11.192:INFO [launcher]: Starting browser internet explorer 9 on SauceLabs
25 08 2015 01:36:11.193:INFO [launcher]: Starting browser internet explorer 6 (Windows XP) on SauceLabs
25 08 2015 01:36:44.710:INFO [launcher.sauce]: internet explorer 6 (Windows XP) session at https://saucelabs.com/tests/b495b74af601433c98dc9896427b7e16
25 08 2015 01:36:45.363:INFO [launcher.sauce]: safari 6 session at https://saucelabs.com/tests/3245f3c3e5e04eceb69351e228a78b60
25 08 2015 01:36:47.463:INFO [launcher.sauce]: internet explorer 9 session at https://saucelabs.com/tests/c5c575f5023b45708990bc3e0140c625
25 08 2015 01:37:41.192:WARN [launcher]: safari 6 on SauceLabs have not captured in 90000 ms, killing.
25 08 2015 01:37:41.203:WARN [launcher]: internet explorer 9 on SauceLabs have not captured in 90000 ms, killing.
25 08 2015 01:37:41.217:WARN [launcher]: internet explorer 6 (Windows XP) on SauceLabs have not captured in 90000 ms, killing.
25 08 2015 01:37:42.119:INFO [launcher]: Trying to start safari 6 on SauceLabs again (1/2).
25 08 2015 01:37:42.272:INFO [launcher]: Trying to start internet explorer 9 on SauceLabs again (1/2).
25 08 2015 01:37:42.282:INFO [launcher]: Trying to start internet explorer 6 (Windows XP) on SauceLabs again (1/2).
```

It just times out. There is no error of any kind when using `jsonp-polling`

When Karma v0.13 and using `transports: [ "polling" ], forceJSONP : true` in Gruntfile and locally patching Karma's server.js to pass `config.forceJSONP` to SocketIO(), the build passes for me.

**Comment by JamesMGreene** [comment] 2015-12-24 15:22
:+1: :confused:

**Comment by Dignifiedquire** [comment] 2016-01-19 21:44
Tracking IE compat in #1564 so closing this issue

**Closed by Dignifiedquire** 2016-01-19 21:44 UTC
Labels: help wanted, type: bug, windows
