### ISSUE TITLE
Chrome have not captured in X ms, killing

### ISSUE THREAD

**Issue by adrianhara** [karma-runner/karma#1206] opened 2014-10-09 17:57 UTC
I've started having this issue on our build machine recently (like, a few days ago). The build is run by a bamboo agent which is basically a windows service which launches "grunt". The grunt task then runs karma (among other things) for the tests. When run by the agent the build fails with this message (after 2 tries).

Running the same command line as the agent starts karma, captures the browser and generally works fine. Increasing the timeout to 3 min instead of 1 didn't help.

Did something change recently in karma that might be causing this behavior when it's run by a service without UI?

l.e.: tried with PhantomJS and IE as well, same. So I'm guessing it's a problem with Karma.

**Comment by Dignifiedquire** [comment] 2015-05-18 19:57
Closing, as this seems to be resolved, please comment / reopen if you are still experiencing this issue.

**Closed by Dignifiedquire** 2015-05-18 19:57 UTC
Labels: type: backlog

**Comment by Wasmoo** [comment] 2015-06-30 20:34
Having trouble with Chrome **Version 43.0.2357.130 m**. Chrome opens with a page that says "Karma Starting", but Karma can't seem to capture the results.

PhantomJS works fine.

Karma v0.12.37

**Comment by Dignifiedquire** [comment] 2015-07-02 18:00
@Wasmoo Please try to open the dev tools and post your console output in general mode and in debug mode please

**Comment by hatton** [comment] 2016-05-25 21:17
For me, the problem turned out to actually just be that some days, the agent really did take longer than 6 seconds to spin up the browser and connect to Karma. Since the agent shares the hardware, sometimes it would get up in time, sometimes it wouldn't.  Changed the timeout to 15 seconds, and all was well.

**Comment by krmannix** [comment] 2017-01-26 21:21
I'm having this issue as well, on a wercker box. Haven't done anything, builds just starting failing beginning of this week. Our timeout is 60s, so that doesn't seem to be an issue

**Comment by krmannix** [comment] 2017-01-26 21:33
I was able to resolve this with [this workaround](https://github.com/karma-runner/karma-chrome-launcher/issues/73#issuecomment-236597429)

**Comment by chrismwendt** [comment] 2017-09-27 00:54
My problem was that **Karma was attempting to execute a nonexistent file** because my `CHROME_BIN` environment variable pointed to a file that did not exist.

**To solve this**, make sure Karma browser environment variables (`CHROME_BIN`, `FIREFOX_BIN`, etc.) are either unset, or point to existing binaries. For a full list, see this GitHub search: [user:karma-runner ENV_CMD][1]. You can check this by running `echo $CHROME_BIN`.

You can also get the **exact shell command that Karma is executing** to try it yourself and see if it fails. To do that, modify `./node_modules/karma/lib/launchers/process.js` like so:

```diff
   }
 
   this._execCommand = function (cmd, args) {
+    log.error([cmd, args.join(' ')].join(' '));
     if (!cmd) {
       log.error('No binary for %s browser on your platform.\n  ' +
```

Here's the output of `env CHROME_BIN=/blah ...`:

![image](https://user-images.githubusercontent.com/1387653/30890636-e5c6f184-a2e2-11e7-9aed-364f41b17cf2.png)

Karma waits, not realizing that the binary doesn't exist.

[1]: https://github.com/search?utf8=%E2%9C%93&q=user%3Akarma-runner+ENV_CMD&type=Code

**Comment by Tenmak** [comment] 2017-10-18 13:56
I had the same issue, and it was not cause by either the `CHROME_BIN` being unset or incorrect, nor the chrome / chromium browser version; and even the `--no-sandbox` option was not helping.

The issue is that I needed to setup the proxy environment variables for my Jenkins job (run through a docker) to ensure `npm` could install dependencies, and I simply forgot to reset the environment variables once the dependencies were downloaded. 

Local headless chrome needed no proxy configuration in my case, hence :

```
export HTTP_PROXY= &&\
export HTTPS_PROXY= &&\
ng test --single-run --progress=false
```

Hope this helps those in trouble

**Comment by luettenberg** [comment] 2017-10-25 16:22
@Tenmak 
Thanks for your hint. That solved our problem too.

**Comment by papaiatis** [comment] 2017-11-02 08:44
Can't believe it was the proxy setting... Thank you @Tenmak  !!

**Comment by TristanMarion** [comment] 2017-12-19 13:55
@Tenmak it worked for me, thanks a lot !

**Comment by vlodko** [comment] 2018-06-15 20:47
this worked for me on build server:
```
    browsers: ['Chrome'],
    browserDisconnectTimeout: 10000,
    browserDisconnectTolerance: 3,
    browserNoActivityTimeout: 60000,
    flags: [
      '--disable-web-security',
      '--disable-gpu',
      '--no-sandbox'
    ]
```

**Comment by arunprasathv** [comment] 2018-06-27 21:50
I'm facing the same issue on build server, it works fine on local machine. tried multiple settings nothing helps. not sure why it fails on build server. 

My karma config settings,

 browsers: ['ChromeNoSandbox'],
    browserDisconnectTimeout: 10000,
    browserDisconnectTolerance: 3,
    browserNoActivityTimeout: 60000,
    // reporters: ['progress', 'coverage'],
    customLaunchers: {
      ChromeNoSandbox: {
        base: 'Chrome',
        flags: [
          '--headless',
          '--disable-gpu',
          '--disable-translate',
          '--disable-extensions',
          '--no-sandbox',   
          '--remote-debugging-port=9222',
        ]
      }
    },

**Comment by mohyeid** [comment] 2018-07-20 00:32
@Tenmak where does these export for thr proxy go? package.json? or karma.config.js? Can you please help?

**Comment by mohyeid** [comment] 2018-08-04 00:33
On my case I am suspecting that when I start chrome outside of karma, it output 
DevTools listening on ws://127.0.0.1:9222/devtools/browser/85057d3a-17c3-455a-a50f-124c4f6f62ea

How do I disable the DevTools?

**Comment by Yrkki** [comment] 2020-06-14 17:02
...
> 
> Local headless chrome needed no proxy configuration in my case, hence :
> 
> ```
> export HTTP_PROXY= &&\
> export HTTPS_PROXY= &&\
> ng test --single-run --progress=false
> ```
> 
> Hope this helps those in trouble
> 
> **EDIT :** It's actually better to simply set a NO_PROXY env variable :
> `export NO_PROXY="localhost, 0.0.0.0/4201, 0.0.0.0/9876" `
> 
...


Saved my life!!! :)

Thank you lots!
