### ISSUE TITLE
Support node 4.0

### ISSUE THREAD

**Issue by charlierudolph** [karma-runner/karma#1577] opened 2015-09-08 22:09 UTC
https://nodejs.org/en/blog/release/v4.0.0/

**Comment by charlierudolph** [comment] 2015-09-08 22:12
Hmm issue may be just node-gyp

**Comment by lygstate** [comment] 2015-09-09 05:31
Why would be node-gyp?

**Comment by charlierudolph** [comment] 2015-09-09 05:45
Nevermind appears to be related to the install scripts of socket-io dependencies similar to #1571

**Comment by Dignifiedquire** [comment] 2015-09-09 14:21
Make some noise on socket.io so they finally bumpt their dependencies to resolve this :( https://github.com/socketio/socket.io/issues/2228#issuecomment-138924694

**Comment by 3rd-Eden** [comment] 2015-09-09 14:23
The root cause of this issue is how horrible the UX of npm is. The build is probably just working fine, but due to the npm output vomit which complains about errors in **optional** dependencies, it makes it look like the installation failed instead of actually being successful.

**Comment by Dignifiedquire** [comment] 2015-09-09 14:25
@3rd-Eden yes I know but everyone thinks the install failed and then comes over here complaining. And even worse, it's actually causing test builds to fail: https://github.com/karma-runner/karma/pull/1579#issuecomment-138909072

**Comment by talltyler** [comment] 2015-09-15 13:35
Now that this is fixed can you please release a new version with a updated socket.io.

**Comment by Dignifiedquire** [comment] 2015-09-15 13:38
@talltyler what makes you think this is fixed? There hasn't been a socket.io release that fixes this as far as I can see.

**Comment by talltyler** [comment] 2015-09-15 13:56
You are correct, it looks like socket.io-client is updated and they are still waiting.
Is there a way around these issues until that happens?

**Comment by Dignifiedquire** [comment] 2015-09-15 13:58
@talltyler you can just use it, they are only optional dependencies that fail when installing, just npm is spitting out way too many warnings about it :(

**Comment by kylecordes** [comment] 2015-09-15 15:33
I am also eager to see this updated.  I hate to see projects stuck with transitive dependencies holding things back, workarounds can be ugly but I think it is better than being stuck.

**Comment by dpsthree** [comment] 2015-09-15 15:40
I ran into this today as well. While I agree with @3rd-Eden it would be nice to have a work around. There is no use attempting to hand wave away errors that aren't actually errors.

**Comment by Dignifiedquire** [comment] 2015-09-15 15:45
Well the solution would be to have someone properly maintaining socket.io...as we sadly can't switch away from it as it still has the best support for old browsers..

**Comment by pmq20** [comment] 2015-09-16 09:01
Adding to the list: nodejs/node#2798.

**Comment by Dignifiedquire** [comment] 2015-09-16 09:24
@pmq20 why? karma is working fine on 4.0 as stated before only optional dependencies of socket.io are failing

**Comment by pmq20** [comment] 2015-09-16 09:45
@Dignifiedquire Oh sorry that I missed the fact that this is just a warning-level failure.

**Comment by mzgol** [comment] 2015-09-21 00:49
FYI: socket.io 1.3.7 is out, it supports Node 4 without any optional deps failing. :) We should get [those lines](https://github.com/karma-runner/karma/blob/c8b5dc35dab9dde82b3fe4b4e335e06fb4ff16c3/.travis.yml#L7-L14) removed from `.travis.yml`.

**Comment by Dignifiedquire** [comment] 2015-09-21 00:54
Sweet

**Comment by Dignifiedquire** [comment] 2015-09-21 08:36
Should be fixed in `0.13.10`

**Closed by Dignifiedquire** 2015-09-21 08:36 UTC
Labels: type: bug-upstream
