### ISSUE TITLE
Angular JS: Error: [$injector:unpr] Unknown provider: $scopeProvider

### ISSUE THREAD

**Issue by realph** [karma-runner/karma#1717] opened 2015-11-19 18:29 UTC
I'm trying to write some unit tests for my app, but I'm running into an issue where I'm getting this error:

> Chrome 46.0.2490 (Mac OS X 10.10.5) app.customer "before each" hook for "should be created successfully" FAILED
>     Error: [$injector:unpr] Unknown provider: $scopeProvider <- $scope <- Customer

My `test.js` file looks like this:

```
describe('app.customers', function() {
  var controller;

  beforeEach(function() {
    module('app', function($provide) {});
    specHelper.injector(function($controller, $q, $rootScope, DataService) {});
  });

  beforeEach(function() {
    sinon.stub(DataService, 'getCustomers', function() {
      var deferred = $q.defer();
      deferred.resolve(mockData.getMockCustomers());
      return deferred.promise;
    });

    controller = $controller('Customer');
    $rootScope.$apply();
  });

  describe('Customer Controller', function() {
    it('should be created successfully', function() {
      expect(controller).to.be.defined;
    });
  });

  specHelper.verifyNoOutstandingHttpRequests();
});
```

I'm not sure why it's looking for `$scopeProvider` as I'm not referencing `$scope.provider` in my test.

I'm pretty new to unit testing in general, so any help with this would be appreciated. Thanks in advance!

Thanks in advance!

**Comment by jrhdoty** [comment] 2015-12-04 23:45
Hi realph,

'Unknown provider errors' occur when the injector cannot find a registered value for a parameter to a function. In this case it has no $scopeProvider with which to create a $scope to inject into the controller. 

When unit testing angular controllers, you will need to create a scope and then pass it as a local to the $controller function. In your code change: 
```javascript
controller = $controller('Customer');
```
to this:
```javascript
var scope = $rootScope.$new();
controller = $controller('Customer', {$scope: scope});
```
and then it should work as intended. This is also a good approach to use when you need to pass route resolve values into a controller for a unit test.

Cheers,
John

**Comment by wesleycho** [comment] 2016-12-07 14:23
Closing this as this looks like purely an Angular 1 testing issue :) . What @jrhdoty said is correct though, this is an issue with properly injecting locals in Angular.

**Closed by wesleycho** 2016-12-07 14:23 UTC
Labels: support
