### ISSUE TITLE
UnhandledRejection when running tests on node v15 (<- unsupported by karma)

### ISSUE THREAD

**Issue by ekdev2** [karma-runner/karma#3570] opened 2020-11-11 17:24 UTC
Hi,

I'm running into the following error when running tests in angular components

karma-server: UnhandledRejection

The issue happens when there is url scss attribute in component scss files

e.g
background: url('image-file-path')

Works fine in lts node

**Comment by johnjbarton** [comment] 2020-11-17 23:37
We support LTS versions.  Please try 16, we don' test on it yet but we need to.

**Comment by mpalourdio** [comment] 2020-11-18 12:43
I'm hitting the exact same error on exact same conditions (url for fonts in scss file) on node latest (v15), but ok on LTS (v14). I wanted to try on v16, but it looks like there no version at the moment. Am I missing something ? The nodejs website does not reference any of v16, nor my 'n'

```bash
$ n 16.0.0

  installing : node-v16.0.0
curl: (22) The requested URL returned error: 404 

  Error: download preflight failed for '16.0.0' (https://nodejs.org/dist/v16.0.0/node-v16.0.0-linux-x64.tar.gz)
```

**Comment by johnjbarton** [comment] 2020-11-18 16:37
Don't use karma on node 15.  I can't help you with your node installation.

**Comment by mpalourdio** [comment] 2020-11-18 16:43
Just wanted to help by testing on node 16 (if it exists), nothing more...

**Comment by johnjbarton** [comment] 2020-11-18 16:47
Ok thanks.  I misread https://nodejs.org/en/about/releases/.  v16 is next year.  So use v14

**Comment by daviian** [comment] 2020-12-17 10:00
We experience the same issue with Node v14.15.2 even without the `url()`. All our tests are not working anymore.

**Comment by sachin1989solanki** [comment] 2020-12-17 10:28
> Don't use karma on node 15. I can't help you with your node installation.

What about node v14.15.2 can karma work with this ?

**Comment by Mayur123-mg** [comment] 2020-12-17 11:40
> Don't use karma on node 15. I can't help you with your node installation.

then what tool i use please suggest

**Comment by devoto13** [comment] 2020-12-17 14:54
Closing as duplicate of #3588. See https://github.com/karma-runner/karma/issues/3588#issuecomment-747484658 for the current recommendation.

**Closed by devoto13** 2020-12-17 14:54 UTC
