### ISSUE TITLE
Upgrading 2.0.2 -> 2.0.3 - promise warning/exception

### ISSUE THREAD

**Issue by DaveO-Home** [karma-runner/karma#3056] opened 2018-06-20 00:01 UTC
### Expected behaviour
No warning : karma executes successfully after the promise fails, just stalls the process......
### Actual behaviour
Getting: 
```js
START:
(node:5540) Warning: a promise was created in a handler at /home/daveo/NetBeans/acceptance-tests-vue/public/node_modules/karma/lib/server.js:122:24 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/home/daveo/NetBeans/acceptance-tests-vue/public/node_modules/bluebird/js/release/promise.js:196:13)
```
### Environment Details

- Karma version (output of `karma --version`):
2.0.3
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.  using gulp - task looks like this;
```js
gulp.task('pat', ['build-development'], done => {
    if (!browsers) {
        global.whichBrowsers = ["ChromeHeadless", "FirefoxHeadless"];
    }

    return runKarma(done);
});

function runKarma(done) {
    let sPromise = new Server({
        configFile: __dirname + '/karma_conf.js',
        singleRun: true
    }, result => {
        var exitCode = !result ? 0 : result;
        if (typeof done === "function") {
            done();
        }
        if (exitCode > 0) {
            process.exit(exitCode);
        }
    }).start();
}
```

**Comment by johnjbarton** [comment] 2018-06-20 00:14
Seems like you need to return the promise:
```js
let sPromise = new Server({...
```
to
```js
return new Server({...
```
or
```js
const sPromise = new Server({...
return sPromise;
```

**Comment by DaveO-Home** [comment] 2018-06-20 01:09
@johnjbarton - pretty quick on the draw.  The sPromise has nothing to do with it, the done() does.
The issue is with karma while starting up the server.  I put the sPromise there just trying to figure out what's going on,  the test eventually finishes successfully.  It's just that the new release interrupts things with the it's own promise warning...see my original post.

**Comment by johnjbarton** [comment] 2018-06-20 01:55
Ok here's another shot: this is a duplicate of #3053

The start() method of Server() has no arguments, so I don't know what your code was doing.  I guess maybe you added the `new`?  In 2.0.2 there was:
```js
Server.start = function (cliOptions, done) {	
  var server = new Server(cliOptions, done)	
  server.start()	
}
```
The feature was fixed in  #3055

**Closed by johnjbarton** 2018-06-20 01:55 UTC

**Comment by DaveO-Home** [comment] 2018-06-20 02:15
@johnjbarton - I'm running on Linux Fedora 28 and node v8.9.4, if that matters.  And I'm not using the static method - I haven't pushed the new version out, but if you want to see the various bundlers/gulp setups I'm using, my demo is github.com/DaveO-Home/embedded-acceptance-tests-vue - this is not a show stopper for me, just an irritation.

**Comment by DaveO-Home** [comment] 2018-06-20 18:48
I down graded to 2.0.2  and the warning did not show.
I upgraded my Canjs app to 2.0.3 and the warning showed.
Comparison of bluebird
```js
├─┬ karma@2.0.3
│ ├── bluebird@3.5.1 
│ └─┬ log4js@2.9.0
│   └─┬ amqplib@0.5.2
│     └── bluebird@3.5.1

├─┬ karma@2.0.2
│ ├── bluebird@3.5.0  deduped
│ └─┬ log4js@2.9.0
│   └─┬ amqplib@0.5.2
│     └── bluebird@3.5.0  deduped
```
Wondering what changed in bluebird.
