### ISSUE TITLE
Karma chrashes with: Fatal error: Wrong length [0.13.16 regression]

### ISSUE THREAD

**Issue by tarjei** [karma-runner/karma#1771] opened 2015-12-30 20:06 UTC
When I run Karma 0.13.16 I get:
30 12 2015 20:53:43.862:INFO [karma]: Karma v0.13.16 server started at http://0.0.0.0:9018/
30 12 2015 20:53:43.873:INFO [launcher]: Starting browser SlimerJS
30 12 2015 20:53:45.053:INFO [Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 SlimerJS/0.9.6]: Connected on socket yVuryGHK6lZFB6ZkAAAA with id 33870595
30 12 2015 20:53:45.510:WARN [web-server]: 404: /v2-files/assets/gotime-logo.svg
Fatal error: Wrong length!

With Karma 0.13.15 the tests run nicely.

After som work, I managed to get this stacktrace:

```
30 12 2015 21:04:44.320:ERROR [karma]: [RangeError: Wrong length!]
RangeError: Wrong length!
  at RangeError (native)
  at strictToLength (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/karma/node_modules/core-js/modules/_typed-array.js:94:36)
  at /var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/karma/node_modules/core-js/modules/_typed-array.js:404:44
  at new Uint8Array (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/karma/node_modules/core-js/modules/es6.typed.uint8-array.js:3:12)
  at allocate (buffer.js:98:17)
  at new Buffer (buffer.js:49:12)
  at BufferPool.reset (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/ws/lib/BufferPool.js:57:26)
  at Receiver.endPacket (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/ws/lib/Receiver.js:247:68)
  at Receiver.opcodes.1.finish (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/ws/lib/Receiver.js:483:12)
  at Receiver.expectHandler (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/ws/lib/Receiver.js:451:33)
  at Receiver.add (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/ws/lib/Receiver.js:95:24)
  at Socket.realHandler (/var/lib/jenkins/jobs/Test_UV_V2/workspace/gt/node_modules/ws/lib/WebSocket.js:800:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

Dependencies:
```
"dependencies": {
    "classnames": "^1.2.0",
    "flux": "2.0.1",
    "history": "1.12.6",
    "immutable": "^3.7.5",
    "katex": "^0.5.0",
    "lodash": "^3.10.1",
    "object-assign": "^2.0.0",
    "qs": "^4.0.0",
    "raven-js": "^1.1.22",
    "rc-tooltip": "^2.6.1",
    "react": "~0.14",
    "react-addons-transition-group": "^0.14.2",
    "react-dnd": "^2.0.2",
    "react-dnd-html5-backend": "^2.0.0",
    "react-dom": "^0.14.2",
    "react-redux": "^4.0.0",
    "react-router": "1.0.1",
    "redux": "^3.0.4",
    "redux-simple-router": "^1.0.2",
    "scriptjs": "^2.5.7",
    "superagent": "^0.19.0"
  },
  "devDependencies": {
    "async": "^1.4.2",
    "babel-core": "6.2.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-react-transform": "^2.0.0-beta1",
    "babel-plugin-transform-runtime": "^6.1.18",
    "babel-polyfill": "6.2.0",
    "babel-preset-es2015": "6.1.18",
    "babel-preset-react": "6.1.18",
    "coffee-loader": "*",
    "coffee-script": "^1.7.1",
    "css-loader": "*",
    "es6-promise": "^3.0.2",
    "extract-text-webpack-plugin": "*",
    "getobject": "^0.1.0",
    "grunt": "*",
    "grunt-bump": "*",
    "grunt-contrib-clean": "^0.4.1",
    "grunt-contrib-concat": "*",
    "grunt-contrib-connect": "~0.7.1",
    "grunt-contrib-copy": "^0.6.0",
    "grunt-contrib-jshint": "^0.11.3",
    "grunt-contrib-less": "*",
    "grunt-contrib-watch": "*",
    "grunt-env": "^0.4.2",
    "grunt-gitinfo": "^0.1.7",
    "grunt-karma": "~0.12.1",
    "grunt-open": "~0.2.3",
    "grunt-sass": "1.1.0",
    "grunt-shell-spawn": "^0.3.0",
    "grunt-webpack": "^1.0.8",
    "imports-loader": "*",
    "jasmine-core": "2.3.*",
    "jasmine-only": "*",
    "js-yaml": "^3.1.0",
    "jshint": "^2.8.0",
    "jshint-loader": "*",
    "json-loader": "^0.5.2",
    "jsxhint": "*",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.1",
    "karma-commonjs": "latest",
    "karma-coverage": "^0.2.6",
    "karma-jasmine": "0.3.6",
    "karma-junit-reporter": "^0.2.2",
    "karma-sauce-launcher": "^0.3.0",
    "karma-script-launcher": "latest",
    "karma-slimerjs-launcher": "^0.1.2",
    "karma-sourcemap-loader": "^0.3.2",
    "karma-spec-reporter": "0.0.20",
    "karma-webpack-with-fast-source-maps": "^1.9.2",
    "load-grunt-tasks": "~0.4.0",
    "react-addons-test-utils": "^0.14.2",
    "react-dnd-test-backend": "^1.0.0",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.2.0",
    "redux-devtools": "^3.0.0",
    "redux-devtools-dock-monitor": "^1.0.1",
    "redux-devtools-log-monitor": "^1.0.1",
    "sinon": "^1.17.2",
    "slimerjs": "~0.9.6-2",
    "style-loader": "latest",
    "url-loader": "latest",
    "webpack": "1.12.8",
    "webpack-dev-server": "1.12.1"
  },

```

Feel free to ping me if you need more information.
Regards,
Tarjei

**Comment by Dignifiedquire** [comment] 2015-12-30 22:23
Duplicate of #1768

**Closed** 2015-12-30 22:23 UTC
