### ISSUE TITLE
Complete TODO listed in client/karma.js line 65

### ISSUE THREAD

**Issue by ajbogh** [karma-runner/karma#2502] opened 2016-12-12 18:18 UTC
### Expected behaviour
Should report stack trace of window reload location, or report file and line with error. Should not include a TODO.

### Actual behaviour
Includes a TODO and reports an obscure message about "Some of your tests did a full page reload."

### Relevant code (master)

      this.onbeforeunload = function () {
        if (!reloadingContext) {
          // TODO(vojta): show what test (with explanation about jasmine.UPDATE_INTERVAL)
          self.error('Some of your tests did a full page reload!')
        }
      }

Related: #1101

**Comment by wesleycho** [comment] 2016-12-14 15:20
Closing as a duplicate of #1101

**Closed by wesleycho** 2016-12-14 15:20 UTC
