### ISSUE TITLE
Unhandled promise rejection: false positive

### ISSUE THREAD

**Issue by andreashuber69** [karma-runner/karma#3683] opened 2021-06-06 16:07 UTC
With karma 6.3.3, I'm getting an `Unhandled promise rejection` error, which looks like a false positive to me. The same code worked fine with karma 4.4.1 (see commit before latest).

The problem can be reproduced as follows:

```
git clone https://github.com/andreashuber69/karma-false-positive-repro.git
cd karma-false-positive-repro
npm ci
npm run test
```

**Comment by devoto13** [comment] 2021-06-06 23:07
Actually this has nothing to do with updating `karma`. You can reproduce this issue by only updating `karma-jasmine`, which in turn would update `jasmine-core` to the version, which includes https://github.com/jasmine/jasmine/pull/1778. So you should probably track https://github.com/jasmine/jasmine/issues/1843, which also shows a workaround for the use cases where you need to trigger unhandled rejection. Unless you specifically testing the logic around error handling, it may be better to re-structure your test in a way that avoids unhandled promise rejection in the first place.

Having said that I would like to see if we can solve `SourceMap position not found for trace` warnings produced by `karma` somehow. You see them because TypeScript has down-leveled the async/await syntax and some of the frames point to the locations in this down-leveled code, which don't map to anything in the original TS code, so that's why the warning. Maybe it would be better to drop such frames from the re-mapped stack trace instead.

**Comment by jginsburgn** [comment] 2021-06-07 05:14
I agree with what @devoto13 answered. I will be closing this issue for now. @andreashuber69, please re-open if you need to.

**Closed by jginsburgn** 2021-06-07 05:14 UTC

**Comment by andreashuber69** [comment] 2021-06-07 05:45
Hi

> Actually this has nothing to do with updating `karma`. You can reproduce this issue by only updating `karma-jasmine`, which in turn would update `jasmine-core` to the version, which includes [jasmine/jasmine#1778](https://github.com/jasmine/jasmine/pull/1778). So you should probably track [jasmine/jasmine#1843](https://github.com/jasmine/jasmine/issues/1843), which also shows a workaround for the use cases where you need to trigger unhandled rejection.

Thanks for your answer. I've had a look at https://github.com/jasmine/jasmine/issues/1777 (linked from 1778), but I don't understand how it is related to my test. In 1777, the rejecting promise **isn't** awaited and so I'd agree that it should lead to an error. In my test however, the rejecting promise is in fact awaited and should thus **not** lead to an error.

**Comment by devoto13** [comment] 2021-06-07 07:17
@andreashuber69 AFAIU the rejection detection logic works synchronously, e.g. if you don't await the rejected `Promise` synchronously, then it will be considered unhandled. In your test case, you have `await new Promise<void>((resolve) => setTimeout(resolve, 100));`, so you create a rejected (not awaited) `Promise` in one tick, before that line, and you await it in another tick after that line when it's too late. If you move `const rejectingPromise = Promise.reject(new Error("Operation failed."));` to after the timeout, then everything should work correctly.

**Comment by andreashuber69** [comment] 2021-06-07 07:43
> @andreashuber69 AFAIU the rejection detection logic works synchronously, e.g. if you don't await the rejected `Promise` synchronously, then it will be considered unhandled....

Thanks again, I've reported the issue in the jasmine repo, see mention above.
