### ISSUE TITLE
Karma@1.7.1 on npm does not match 1.7.1 source on GitHub

### ISSUE THREAD

**Issue by kmashint** [karma-runner/karma#2827] opened 2017-09-07 02:49 UTC
### Expected behaviour
npm install karma@1.7.1  using https://registry.npmjs.org/ should have the same package.json dependencies as the karma-1.71.zip.

### Actual behaviour
`$ npm view karma@1.7.1 dist.tarball`
https://registry.npmjs.org/karma/-/karma-1.7.1.tgz
`$ curl -o karma-1.7.1-npm.com.tgz https://registry.npmjs.org/karma/-/karma-1.7.1.tgz`
And then inspecting the tgz file it shows package.json dependencies with lodash: ^3.8.0 instead of ^4.x.y.

### Environment Details
$ node --version
v6.11.1
$ npm --version
3.10.10

### Steps to reproduce the behaviour
As above.

Is this a problem in publishing to registry.npmjs.org?

**Comment by johnjbarton** [comment] 2017-10-16 16:26
Yes, the npm distribution is somehow messed up.

The github source package.json
https://github.com/karma-runner/karma/blob/master/package.json
has
`"version": "1.7.0",`
and dependencies including:
` "lodash": "^4.17.4",`
But the npm distro has package.json with 
`version 1.7.1`
and dependencies including:
`"lodash": "^3.8.0",`

How can we fix this?

**Comment by johnjbarton** [comment] 2017-10-17 17:04
I think the problem here is that the 1.7.1 branch is not merged into HEAD

**Comment by EzraBrooks** [comment] 2017-11-25 02:05
I renamed this issue to make it more general, as there are other issues caused by this failed deployment.

**Comment by dignifiedquire** [comment] 2017-11-25 14:29
karma 1.7.1 is correct on npm. 1.7.1 was released with "old" lodash@3 because moving to 4 is breaking change. `master` contains multiple breaking changes, so I  cut a release for 1.7.1 which __only__ contains [this commit](https://github.com/karma-runner/karma/commit/ea32194a6c3697a71ac8098396e4d54d17ea9ba0). The branch 1.7.1 is incorrect now as master was never supposed to be merged into it, only the tag is correct.

**Closed by dignifiedquire** 2017-11-25 14:29 UTC

**Comment by wilsonge** [comment] 2017-12-28 12:57
@dignifiedquire can you clean up the fact there are multiple tags for 1.7.1 then - and not containing the same source code - https://github.com/karma-runner/karma/compare/v1.7.1...1.7.1

**Comment by dignifiedquire** [comment] 2017-12-28 13:53
@wilsonge thank you for pointing that out, should be fixed now and tags correct

**Comment by wilsonge** [comment] 2017-12-28 14:31
Thanks :)
