### ISSUE TITLE
--auto-watch broken in 3.1.3 (works in 3.1.1)

### ISSUE THREAD

**Issue by jhildenbiddle** [karma-runner/karma#3234] opened 2018-12-15 17:34 UTC
### Expected behaviour
* Karma will detect file change, automatically rerun tests with `--auto-watch` option, and changes will be reflected in the test output.

### Actual behaviour
1. Saving changes to a test file triggers tests to rerun but changes are not reflected. Saving the test file a second time (without making changes) triggers tests to rerun again, this time with changes reflected.
1. Saving changes to a source file triggers tests to rerun but changes are not reflected. Only saving a test file will result in changes to a source file being reflected.

### Environment Details

- Karma version (output of `karma --version`): 3.1.3
- Relevant part of your `karma.config.js` file: See [css-vars-ponyfill/karma.conf](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/karma.conf.js)

### Steps to reproduce the behaviour

1. Clone [css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) release [1.16.0](https://github.com/jhildenbiddle/css-vars-ponyfill/releases/tag/v1.16.0). This version is running Karma 3.1.3
2. On CLI: `npm run dev`. This runs both the build and test tasks in watch mode.
3. Edit one of the files in the `/tests` directory. Notice the file has to be saved twice in order for changes to be reflected.
4. Edit one of the files in the `/src` directory. Notice the changes are not reflected until a file in `/tests` is saved.
5. Downgrade to Karma 3.1.1: `npm i -D karma@3.1.1`
6. Perform steps 3 and 4 again. Notice that changes to test and source files are reflected immediately after saving (as expected).

**Comment by hunthunthunt** [comment] 2018-12-17 15:42
I can confirm I'm seeing the same with the `3.1.3` release. If I pin the version to `3.1.1` in `package.json` then the bug goes away.

**Comment by cdbkr** [comment] 2018-12-17 15:52
Same here. Downgrading to 3.1.1 works as expected (tests effectively re-run)

**Comment by devoto13** [comment] 2018-12-17 17:24
This seems to be a duplicate of https://github.com/karma-runner/karma/issues/3234, which is fixed by https://github.com/karma-runner/karma/pull/3230. Just wait for a new release.

**Comment by jhildenbiddle** [comment] 2018-12-23 06:05
Appears to be fixed in 3.1.4.

Thanks for the quick turnaround! 🎉

**Closed** 2018-12-28 17:22 UTC
