### ISSUE TITLE
IE fails when executing tests with local storage

### ISSUE THREAD

**Issue by naccarati** [karma-runner/karma#2416] opened 2016-10-24 16:47 UTC
Hello,

I'm trying to execute my unit tests in a remote host. When I execute it on the machine, everything goes fine, however, when I execute it remotely or as a service, I'm experience some sort of error with local storage in IE.

**Error:**

Error: This function is not supported on this system.
       at Storage (c:/xampp/htdocs/scripts/tests/unit/_test.js:1248:2)
       at DoPlugins (c:/xampp/htdocs/scripts/tests/unit/_test.js:1963:2)
       at Anonymous function (c:/xampp/htdocs/scripts/tests/unit/lib/modules/File.spec.js:10:3)
TypeError: Unable to get property 'timeParting' of undefined or null reference
       at Anonymous function (c:/xampp/htdocs/scripts/tests/unit/lib/modules/File.spec.js:17:3)

**### Environment Details**
- Karma version (output of `karma --version`): karma": "^0.13.22"
- Relevant part of your `karma.config.js` file:
  frameworks: ['jasmine'],
  reporters: ['spec'],
  browsers: ['PhantomJS', 'Chrome', 'Firefox', 'IE'],
  files: [
      './tests/unit/_test.js',
      './tests/unit/**/**/*.js'
  ],
  singleRun: true,
  autoWatch: false

Thanks for the help.

**Comment by vivganes** [comment] 2016-10-26 14:04
@naccarati Can you please specify the version of your Internet Explorer and the OS version too?  Something of this sort was identified as a bug in IE 11 and a patch was released to solve this issue.

More details can be found here: http://stackoverflow.com/questions/21155137/javascript-localstorage-object-broken-in-ie11-on-windows-7

In case you are using the affected version, can you try installing the patch sugested in the above stackoverflow thread and try running again?

**Comment by naccarati** [comment] 2016-10-26 16:36
Hello @vivganes,

I've tried in IE10 and IE11 on win 7 and 8.1, both 32bits.

Tried to install the patch but still having the same problem.

Thanks for the help.

**Comment by maksimr** [comment] 2016-12-02 08:20
@naccarati look at https://connect.microsoft.com/IE/feedback/details/794531/getting-an-exception-this-function-is-not-supported-on-this-system-when-using-localstorage-when-ie-started-under-the-windows-service

Close as duplicate of https://github.com/karma-runner/karma-ie-launcher/issues/10

**Closed by maksimr** 2016-12-02 08:20 UTC
