### ISSUE TITLE
$q.when not resolved inside Karma

### ISSUE THREAD

**Issue by yoorek** [karma-runner/karma#1102] opened 2014-06-15 18:16 UTC
I use **$q.when** to wrap around other lib promises. 
It works like a charm but when i try to run it inside Karma the promise failes to resolve (**done()** is never executed) even if I ran **$digest** and even after timeout.
Here is sample code: 

    describe('PouchDB', function () {
    var $q, $rootScope;

    beforeEach(inject(function (_$rootScope_, _$q_) {
        $rootScope = _$rootScope_;
        $q = _$q_;
    }));

    it("should run", function (done) {

        function getPromise() {
            var deferred = Q.defer();       
            deferred.resolve(1);
            return deferred.promise;
        }

        $q.when(getPromise())
            .then(function () {
                done();   // this never runs
            });

        $rootScope.$digest();
    });

Why? What is the cause of this? I really cannot get it.

**Comment by Dignifiedquire** [comment] 2015-06-26 21:23
This has nothing to do with karma itself, so closing.

**Closed by Dignifiedquire** 2015-06-26 21:23 UTC
Labels: type: backlog

**Comment by Sturgelose** [comment] 2015-12-12 17:04
@yoorek , I know that the issue is rather old, but did you figure out the origin of the issue? angular-pouchdb uses the $q.when to wrap the pouchdb and well, I'm having exactly the same issue. Strange stuff is that running the same code without karma works perfectly!
