### ISSUE TITLE
You need to include some adapter that implements __karma__.start method!

### ISSUE THREAD

**Issue by xcsweb** [karma-runner/karma#3217] opened 2018-11-21 04:05 UTC
### Environment Details

- "karma": "^3.1.1"
// Karma configuration
// Generated on Fri Nov 16 2018 16:57:51 GMT+0800 (GMT+08:00)
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine','chai'],

    // list of files / patterns to load in the browser
    files: [
      'test/**/*.spec.js'
    ],
    preprocessors: {
      'test/**/*.spec.js': ['babel']
    },
    // list of files / patterns to exclude
    exclude: [
    ],

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],

    // web server port
    port: 8085,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}

![image](https://user-images.githubusercontent.com/20693737/48818260-6d00c380-ed85-11e8-98ab-ddb06ed45b34.png)

### Steps to reproduce the behaviour
![image](https://user-images.githubusercontent.com/20693737/48818222-33c85380-ed85-11e8-8f2b-3ce296a0cd78.png)
![image](https://user-images.githubusercontent.com/20693737/48818282-87d33800-ed85-11e8-8222-53049f590f29.png)

![image](https://user-images.githubusercontent.com/20693737/48818273-7e49d000-ed85-11e8-806a-5b8c86bb616e.png)
how can solve this problem

**Comment by rogeriopvl** [comment] 2018-11-21 08:49
Duplicate of #3198

**Comment by johnjbarton** [comment] 2018-11-21 16:38
Set `logLevel: config.LOG_INFO`.  Do not use `--singleRun`.  When the server is up, open the browser and use devtools to debug.  Your html page is missing the karma-jasmine adapter or it is mangled or not loading.

**Closed by johnjbarton** 2018-11-21 16:38 UTC
