### ISSUE TITLE
Karma waits ~20 secs before exiting when using public api

### ISSUE THREAD

**Issue by pazams** [karma-runner/karma#1822] opened 2016-01-23 14:37 UTC
Karma waits ~20 secs before exiting when using public api.
Happens to me with karma 0.13.19.
Downgrading to 0.12.x fixes it. 
Looks like it was solved previously https://github.com/karma-runner/karma/issues/1035. ?

**Comment by Dignifiedquire** [comment] 2016-01-23 15:15
I expect this to be the same issues as #1788

**Comment by lukaselmer** [comment] 2016-01-27 13:38
Seems like the issue is resolved by using socket.io 1.4.5 https://github.com/socketio/socket.io/commit/b3fc530abefd384b3a89ff5493e97f3ef85098d4! Thanks!

**Comment by Dignifiedquire** [comment] 2016-01-27 13:45
@lukaselmer thanks for the confirmation. Closing this then.

**Closed by Dignifiedquire** 2016-01-27 13:45 UTC

**Comment by ChALkeR** [comment] 2016-02-26 21:48
Was it really fixed? Still looks occasionally hanging for about that time to me, with karma@0.13.21 and socket.io@1.4.5.

**Comment by SerialVelocity** [comment] 2016-03-14 18:20
@dignifiedquire @ChALkeR This is still happening for us too with karma@0.13.19 and socket.io@1.4.5

**Comment by travisperson** [comment] 2016-03-23 15:17
I am also running into this issue with karma@0.13.21 and socket.io@1.4.5

**Comment by dignifiedquire** [comment] 2016-03-23 16:59
As said in the other issue, I'm not able to reproduce this with the latest versions, so please provide me with an example that reproduces this consistently

**Comment by ChALkeR** [comment] 2016-03-23 19:26
@dignifiedquire https://github.com/qmlweb/qmlweb/blob/master/gulpfile.js#L81 --- should be reproducible without that line. Sorry, no smaller testcase atm.
