### ISSUE TITLE
Headless Chrome version detected to be 0.0.0 on Linux

### ISSUE THREAD

**Issue by applecool** [karma-runner/karma#2923] opened 2018-01-26 15:41 UTC
### Expected behaviour
Karma should display a real version number of Chrome Headless.

### Actual behaviour
It always displays `HeadlessChrome 0.0.0 (Linux 0.0.0)`.

### Environment Details

- OS version: `Ubuntu 16.04.3 LTS`
- Karma version (output of `karma --version`):
   `2.0.0`
- Relevant part of your `karma.config.js` file
  `browsers: ['ChromeHeadless']`

### Steps to reproduce the behaviour

1. Specify `browsers: ['ChromeHeadless']` in the Karma config.
2. Run any tests.
3. Look at the terminal.

Console Output: 
```
26 01 2018 07:24:08.869:INFO [launcher]: Starting browser ChromeHeadless
26 01 2018 07:24:09.145:INFO [HeadlessChrome 0.0.0 (Linux 0.0.0)]: Connected on socket rmz46iav0YsA7WiUAAAA with id 10185539
```

**Comment by lusarz** [comment] 2018-02-12 11:30
It may be related with:
https://github.com/3rd-Eden/useragent/issues/118

**Comment by mmermerkaya** [comment] 2018-05-02 23:57
In my project, HeadlessChrome version detection works fine in Karma 2.0.0, but doesn't work in 2.0.2.

**Comment by mmermerkaya** [comment] 2018-05-03 15:01
Looks like it's because [useragent](https://github.com/3rd-Eden/useragent) was downgraded from 2.3.0 to 2.2.1 in https://github.com/karma-runner/karma/pull/2937, most likely because of this bug: https://github.com/3rd-Eden/useragent/issues/120.

So it's either proper Windows versions or proper HeadlessChrome version... :confused:

**Comment by rkuzsma** [comment] 2018-11-03 15:51
Dupe of https://github.com/karma-runner/karma/issues/2762

**Comment by mgol** [comment] 2018-11-10 19:49
This issue should be closed as it's a duplicate and the issue it duplicates is already closed.

**Closed** 2018-11-12 15:22 UTC
