### ISSUE TITLE
The DOM by Karma rendered is not the same as the DOM by Angular rendered

### ISSUE THREAD

**Issue by leochen0818** [karma-runner/karma#3700] opened 2021-09-22 14:02 UTC
I wrote a test case to test the form that I make with Angular Template Driven Forms, but it failed because the DOM by Karma rendered is not the same as the DOM by Angular rendered.

These are the captures:

![testing result](https://i.imgur.com/qm2RoUy.png)

![testing result](https://i.imgur.com/lIKWpXf.png)

![testing result](https://i.imgur.com/2RQeN4P.png)

> The background one was running by Angular, another one was running by Karma.

Here is the sample code: [https://github.com/leochen0818/angular-30days-form-and-testing/blob/fcc478d2191710c9bd5374d46ceeb785e5562993/src/app/app.component.spec.ts#L304-L309](https://github.com/leochen0818/angular-30days-form-and-testing/blob/fcc478d2191710c9bd5374d46ceeb785e5562993/src/app/app.component.spec.ts#L304-L309)

**Comment by devoto13** [comment] 2021-09-23 10:12
Thanks for the report!

I do observe the same problem and it does look wrong to me. I'm not sure what's causing it though. However, the problem seems to be either in Angular itself or the Angular plugin for karma which is provided as part of Angular CLI. What karma core does is that it just loads your tests into browser, runs them, and displays the result and I don't think this issue is caused by the bug in karma core (I may be wrong of course).

I think you will have a better chance of getting help either in [Angular support channels](https://github.com/angular/angular#community) or [Angular CLI support channels](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem). Please post back here if you manage to figure out what is causing this problem.

**Comment by leochen0818** [comment] 2021-09-23 12:02
> Thanks for the report!
> 
> I do observe the same problem and it does look wrong to me. I'm not sure what's causing it though. However, the problem seems to be either in Angular itself or the Angular plugin for karma which is provided as part of Angular CLI. What karma core does is that it just loads your tests into browser, runs them, and displays the result and I don't think this issue is caused by the bug in karma core (I may be wrong of course).
> 
> I think you will have a better chance of getting help either in [Angular support channels](https://github.com/angular/angular#community) or [Angular CLI support channels](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem). Please post back here if you manage to figure out what is causing this problem.

Thank you for your reply. I submit the issue to Angular CLI support channels.

The link is: [https://github.com/angular/angular-cli/issues/21803](https://github.com/angular/angular-cli/issues/21803) 

Maybe we can found the cause there.

**Comment by devoto13** [comment] 2021-11-13 22:59
I'm going to close this issue in favour of https://github.com/angular/angular-cli/issues/21803 as it seems to be bug in Angular and in its current state there is nothing we can do about it in the karma repo.

**Closed by devoto13** 2021-11-13 22:59 UTC
