### ISSUE TITLE
Karma is not able to run test cases on phantomJS

### ISSUE THREAD

**Issue by kausikram** [karma-runner/karma#558] opened 2013-05-28 11:32 UTC
I have been trying to get Karma to run tests on PhantomJS for the last couple of hours and seem to be stuck at it. I had my entire suit run tests in Chrome and it ran without a quirk. on trying to run it with Karma, it would just not run.

I was running phantomjs 1.9 and then i reverted to 1.8. i tried installing it from the distributed binary from the phantomjs site and i also tried to install it through npm. But i had no avail in any of the combinations. I am on a 64bit Ubuntu machine.

I am pretty sure my configurations are correct and i checked phantomjs which again seems to be working.

Am i missing something here. or is this some bizarre bug.

I am attaching my debug logs below.

``` log
DEBUG [reporter]: Using reporter "dots".
DEBUG [reporter]: Using reporter "junit".
INFO [karma]: Karma server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
DEBUG [launcher]: Creating temp dir at /tmp/testacular-86450027
DEBUG [launcher]: phantomjs /tmp/testacular-86450027/capture.js
DEBUG [watcher]: Resolved files:
    /home/kausikram/lib/node_modules/karma/adapter/lib/jasmine.js
    /home/kausikram/lib/node_modules/karma/adapter/jasmine.js
    /home/kausikram/Projects/scloud/src/main/webapp/resources/jquery/jquery.js
    /home/kausikram/Projects/scloud/src/main/webapp/resources/jquery/jquery.dynoform.js
[...]

DEBUG [web server]: serving: /home/kausikram/lib/node_modules/karma/static/client.html
DEBUG [web server]: serving: /home/kausikram/lib/node_modules/karma/static/testacular.js
DEBUG [karma]: New browser has connected on socket s2jUXmnylvNYdQux4Wc2
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
DEBUG [launcher]: Process PhantomJS exitted with code 1
ERROR [launcher]: Cannot start PhantomJS

DEBUG [launcher]: Cleaning temp dir /tmp/testacular-86450027
INFO [launcher]: Trying to start PhantomJS again.
DEBUG [launcher]: Creating temp dir at /tmp/testacular-86450027
DEBUG [launcher]: phantomjs /tmp/testacular-86450027/capture.js
DEBUG [web server]: serving: /home/kausikram/lib/node_modules/karma/static/client.html
DEBUG [web server]: serving: /home/kausikram/lib/node_modules/karma/static/testacular.js
DEBUG [karma]: New browser has connected on socket 3qsGGwLPK5ogNJs_4Wc3
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
DEBUG [launcher]: Process PhantomJS exitted with code 1
ERROR [launcher]: Cannot start PhantomJS
```

**Comment by gsakhardande** [comment] 2015-04-01 10:59
The issue got resolved for me in Ubuntu 14.04 by deleting the `node_modules` directory from the project (which had been checked-in by someone else using a Macbook). I ran `npm install` again and the `node_modules` directory was recreated. We have also added the 'node_modules' directory to `.gitignore`

**Comment by joseph-jja** [comment] 2015-04-29 21:02
I have developers that I work with that are having a similar issue to this.  We get the message about a disconnect and no tests are run.  I tracked it down to karma/lib/browser.js and line 42: 

log.warn('Disconnected (%d times)' + (reason || ''), self.disconnectsCount);

It happens to me about 1 in every 100 or so runs, it does not happen on jenkens, but it happens on some developers machines almost every run.  

Users can't kill it with Control-C, so I upped the timeout noActivityTimeout to 60000 and now they can hit Control-C to kill it if they do it within the 60 seconds.  

The reason is ', because no message in ' + noActivityTimeout + ' ms.'

In some cases it looks like a test may be failing because of a bad template or something but it does not throw an error, it just hangs.  In other cases it just hangs for no reason.

I change

**Comment by Deepakdubey90** [comment] 2015-05-28 13:36
Hi, 
i' am writing unit Test-Case  for UI by  using PhantomJs with Karma(angularJs) . but got an error on console .
Error >>>>>>>>>>>>>>>>>
PhantomJS 1.9.8 (Linux): Executed 36 of 39 SUCCESS (0 secs / 0.104 secs)
PhantomJS 1.9.8 (Linux) ERROR
  ""Some of your tests did a full page reload!""
PhantomJS 1.9.8 (Linux): Executed 36 of 39 ERROR (0.141 secs / 0.104 secs)
npm ERR! Test failed.  See above for more details.
Error>>>>>>>>>>>>>>>>>

i'm not able execute all of the test case because of this error(skip few of the test case while executing.) how to debug for error 
""Some of your tests did a full page reload!"".
please suggest me fix this issue.

**Comment by Deepakdubey90** [comment] 2015-06-18 12:40
Hey, guys how can i debug the jasmine unit test case to trace error..
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  Some of your tests did a full page reload!
PhantomJS 1.9.8 (Linux 0.0.0): Executed 36 of 153 ERROR (0.15 secs / 0.112 secs)

Please suggest me the root cause of this.

**Comment by joseph-jja** [comment] 2015-06-18 23:07
One scenario I have found that is reproducable is when a developer checks in a file that depends on a file that is not checked into source.  The tests fail when they try to find that file.  So in terms of AMD / requirejs: 

moduleA.js would have this:
define(['moduleB'], function(b) { console.log(b); });

then a test would define(['moduleA'], function(a) { describe .. jasmine test stuff....

moduleB does not exist so then error 

4mRunning "karma:common" (karma) task[24m
[32mINFO [karma]: [39mKarma v0.12.35 server started at http://localhost:37117/
[32mINFO [launcher]: [39mStarting browser PhantomJS
[32mINFO [PhantomJS 1.9.8 (Linux 0.0.0)]: [39mConnected on socket H6Mhb7BTo19vIi_awUzY with id 84202369
PhantomJS 1.9.8 (Linux 0.0.0) LOG: 'Test port: 37117'

[33mWARN [web-server]: [39m404: /base/src/moduleB.js
PhantomJS 1.9.8 (Linux 0.0.0) ERROR: 'There is no timestamp for /base/src/moduleB.js!'

[33mWARN [PhantomJS 1.9.8 (Linux 0.0.0)]: [39mDisconnected (1 times), because no message in 10000 ms.

**Comment by VikrantGodse** [comment] 2015-06-19 07:21
Hey  Hi....I have also faced the same issue...just anywhere in your test cases you might have used "SpyOn(window, 'location')" and immediate after that u have not called any jasmine matcher like "toHaveBeenCalled" that results into reloading issue.....also check that all dependencies are spelled and injected properly....I am sure you'll get the solution...!

**Comment by Deepakdubey90** [comment] 2015-06-19 09:29
@VikrantGodse thanks, its working.

**Comment by marcofranssen** [comment] 2015-11-19 15:45
Same issue here...

Node: **4.2.2**
Karma **0.13.15**
Karma-phantomjs-launcher **0.2.1**
phantomjs **1.9.18**

This is how we run it

```bash
karma start "web/js2/test/karma.conf.js" --no-colors --single-run --log-level info --reporters dots
19 11 2015 15:22:07.682:INFO [karma]: Karma v0.13.15 server started at http://localhost:9877/
19 11 2015 15:22:07.695:INFO [launcher]: Starting browser PhantomJS
19 11 2015 15:22:27.706:WARN [launcher]: PhantomJS have not captured in 20000 ms, killing.
19 11 2015 15:22:27.722:INFO [launcher]: Trying to start PhantomJS again (1/2).
19 11 2015 15:22:47.729:WARN [launcher]: PhantomJS have not captured in 20000 ms, killing.
19 11 2015 15:22:47.739:INFO [launcher]: Trying to start PhantomJS again (2/2).
19 11 2015 15:23:07.743:WARN [launcher]: PhantomJS have not captured in 20000 ms, killing.
19 11 2015 15:23:07.749:ERROR [launcher]: PhantomJS failed 2 times (timeout). Giving up.
```

Running phantomjs manually like this seems to work since it just gives me the `phantomjs REPL`.

```bash 
node_modules/phantomjs/bin/phantomjs
phantomjs> 
```

**Comment by KenNgo** [comment] 2015-11-20 09:47
I got an issue with phantomjs/ karmajs:

INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (1/2).
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (2/2).
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
ERROR [launcher]: PhantomJS failed 2 times (timeout). Giving up.
[16:14:42] 'test' errored after 3.05 min
[16:14:42] Error: 1

node --version v0.12.7
Karma v0.12.37
Karma-phantomjs-launcher 0.2.0
phantomjs 1.9.18

**Comment by maxm450** [comment] 2015-12-03 20:01
Same here 

03 12 2015 14:56:09.385:WARN [karma]: No captured browser, open http://localhost:9876/
03 12 2015 14:56:09.405:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
03 12 2015 14:56:09.409:INFO [launcher]: Starting browser PhantomJS
03 12 2015 14:56:10.886:ERROR [launcher]: Cannot start PhantomJS

03 12 2015 14:56:11.005:INFO [launcher]: Trying to start PhantomJS again (1/2).
03 12 2015 14:56:12.349:ERROR [launcher]: Cannot start PhantomJS

03 12 2015 14:56:12.387:INFO [launcher]: Trying to start PhantomJS again (2/2).
03 12 2015 14:56:13.369:ERROR [launcher]: Cannot start PhantomJS

03 12 2015 14:56:13.371:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.

Karma v0.13.10
Karma-phantomjs-launcher 0.2.1
phantomjs 1.9.18

**Comment by joseph-jja** [comment] 2015-12-24 23:19
I have tried adding lots of options to this and found that when phantomjs does this it is a problem in the code.  Unfortunately finding out where is a bit more difficult, you have to set the logLevel to config.DEBUG and then run in verbose debugging mode. It usually spits out more info there.

I recommend running jshint / jslint or eslint on both your code AND your tests and looking for any undefined variables or other syntax errors.  Things like extra commas and missing semicolons can cause issues in phantomjs/karma.  Make sure any async code is coded correctly.  

Lastly, make sure you do not have an it with no expects in it if you are using jasmine.  We found that to be problematic.  Ultimately though one of the tests is bad.

**Comment by niemyjski** [comment] 2016-01-07 18:06
I recently started running into this issue as well: https://ci.appveyor.com/project/Exceptionless/exceptionless-ui/build/2.2.625

**Comment by karthikorsu** [comment] 2016-03-11 11:56
How to configure karma_start.js to disable web security and local to remote url access using phantom launcher?

**Comment by MakkaHareesh** [comment] 2016-03-12 04:06
hareesh@hareesh-VPCEA12EN:~/Desktop/test/test$ gulp test
[09:34:24] Working directory changed to ~/Desktop/pstnwebapp
[09:34:25] Using gulpfile ~/Desktop/pstnwebapp/gulpfile.js
[09:34:25] Starting 'start:server:test'...
[09:34:25] Finished 'start:server:test' after 146 ms
[09:34:25] Starting 'test'...
[09:34:26] Server started http://localhost:9001
[09:34:26] LiveReload started on port 35729
[09:34:26] Starting Karma server...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use 
  server = new Server(config, [done])
  server.start()
instead.
12 03 2016 09:34:28.014:ERROR [config]: File /home/hareesh/Desktop/pstnwebapp/karma.conf.js does not exist!
[09:34:28] 'test' errored after 2.09 s
[09:34:28] Error in plugin 'gulp-karma'
karma exited with code 1

**Comment by jamesongamble** [comment] 2016-03-30 18:16
So, i've been using ES6 in my code ( function arrows, const, and let) and it is those lines that karma actually breaks on. It looks like you need another preprocessor to transpile the ES6 before karma can run properly. I'm assuming this module will probably fix the errors for you:

https://github.com/babel/karma-babel-preprocessor

but i'm in the process of installing that right now. Will update later. Also, setting "logLevel: config.DEBUG," in your karma.confg.js and running grunt test with a "-v" flag also helped me figure out what lines it was really breaking on.

**Comment by antonyh** [comment] 2016-09-28 13:37
I solved this issue by deleting the `node_modules` folder and running `npm install` again - PhantomJS and Karma ran flawlessly following this cleanup.

PhantomJS 2.1.1 on Linux
Karma 1.2.0
Grunt 0.4.5

**Comment by allenhwkim** [comment] 2016-10-19 02:03
I solved this issue by reinstalling node_modules
```
karma 
karma-chrome-launcher
karma-jasmine
karma-ng-html2js-preprocessor
karma-phantomjs-launcher
phantomjs
```

**Comment by dusterio** [comment] 2016-10-27 09:11
@antonyh sounds awfully irrational though, sounds like Microsoft :( good software shouldn't magically fix itself upon restart or reinstall.

**Comment by ds009** [comment] 2016-11-19 09:02
I tried to change config by increasing browserNoActivityTimeout and browserDisconnectTimeout,etc. but phantomjs disconnection errors were still there.

Then enable swap space worked, as this answer said: https://stackoverflow.com/a/32444643

shell script for automation

> fallocate -l 4G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
bash -c 'echo "/swapfile none swap sw 0 0" >> /etc/fstab'


Wish it can save your time

**Comment by MarcinMilewski** [comment] 2016-12-30 11:37
I've got weird problem: run single test iteration works, but  in continous mode doesn't,  that means after starting browser PhantomJS, last log is Connected on socket ... and any test don't run.

**Comment by ethaneron** [comment] 2017-02-09 18:01
Hello everyone,  I ran into this same (frustrating) issue and discovered the problem was in the gulp config I was using to run karma / PhantomJS.  When I changed singleRun: false -> true it started working for me again:

```
var gulp = require('gulp');
var Server = require('karma').Server;

// Run test once and exit
gulp.task('test', function (done) {
    new Server({
        configFile: __dirname + '/karma.conf.js',
        singleRun: true
    }, done).start();
});
```

**Comment by tiefling** [comment] 2017-04-05 23:58
I've just hit this - works fine on my local machines but won't run on the Visual Studio Online CI server. It used to work fine but has recently just stopped...

    2017-04-04T18:24:11.4691955Z [18:24:11] Starting 'karma-server'...
    2017-04-04T18:24:22.7975588Z [32m04 04 2017 18:24:22.796:INFO [framework.browserify]: [39mbundle built
    2017-04-04T18:24:22.8435587Z [32m04 04 2017 18:24:22.843:INFO [karma]: [39mKarma v1.5.0 server started at http://0.0.0.0:9876/
    2017-04-04T18:24:22.8435587Z [32m04 04 2017 18:24:22.843:INFO [launcher]: [39mLaunching browser PhantomJS with unlimited concurrency
    2017-04-04T18:24:22.8495591Z [32m04 04 2017 18:24:22.849:INFO [launcher]: [39mStarting browser PhantomJS
    2017-04-04T18:25:22.8598561Z [33m04 04 2017 18:25:22.859:WARN [launcher]: [39mPhantomJS have not captured in 60000 ms, killing.
    2017-04-04T18:25:24.8616444Z [33m04 04 2017 18:25:24.861:WARN [launcher]: [39mPhantomJS was not killed in 2000 ms, sending SIGKILL.
    2017-04-04T18:25:26.8628686Z [33m04 04 2017 18:25:26.861:WARN [launcher]: [39mPhantomJS was not killed by SIGKILL in 2000 ms, continuing.

I've already looked at a similar article on SO in relation to TeamCity (http://stackoverflow.com/questions/40382241/teamcity-phantomjs-have-not-captured-in-60000-ms-killing) but none of the suggestions there helped me - If there is a version conflict of some kind I'm not sure what I can do about it as it is a cloud server.

To complicate matters, trying using Chrome and Firefox results in similar errors, so Karma won't seem to run at all.

**Comment by tiefling** [comment] 2017-04-06 01:10
I fixed this by fixing karma version at 1.3.0 (1.3.0 instead of ^1.3.0)

There must be  a bug in 1.5.0, which it was using before on the CI server (my local copy is 1.3.0).

Any updates?

**Comment by sgsasha** [comment] 2017-12-20 14:27
If someone facing this problem in angular/cli, I've fixed this problem by uncommenting this lines in polyfill.ts:
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

**Comment by devoto13** [comment] 2020-05-19 21:38
This issue accumulated a lot of different problems and is not actionable now. It has not been active for 2.5 years and PhantomJS [has been archived](https://phantomjs.org) since then. If you still experience issues with PhantomJS consider migrating to Chrome Headless or Firefox Headless.

**Closed by devoto13** 2020-05-19 21:38 UTC
Labels: needs: investigation
