### ISSUE TITLE
Change the style of main website to be dark mode

### ISSUE THREAD

**Issue by shanewaz-abbas** [karma-runner/karma#3582] opened 2020-12-14 03:47 UTC
http://karma-runner.github.io/5.2/index.html

Since it's a developer tool, it would be really helpful to have dark mode support. The current website burns my eyes.

**Comment by johnjbarton** [comment] 2020-12-14 20:25
Please send a pull request.

**Comment by shanewaz-abbas** [comment] 2020-12-14 20:29
Sure

**Comment by devoto13** [comment] 2020-12-16 20:39
I'm going to close it as duplicate of #3576 because it has more discussion. But PR is still welcome!

**Comment by devoto13** [comment] 2020-12-16 20:39
Oh, never mind. It was about the website.

**Comment by shanewaz-abbas** [comment] 2020-12-16 21:08
I'm almost done. Should have a pr soon.

**Comment by devoto13** [comment] 2020-12-18 18:21
Fixed by https://github.com/karma-runner/karma-runner.github.com/pull/78. Thanks @shane99a!

**Closed by devoto13** 2020-12-18 18:21 UTC

**Comment by shane99a** [comment] 2020-12-19 01:12
Awesome. Thank you !!

**Comment by jdugas** [comment] 2023-05-03 12:15
Dark mode appears to no longer work. 
![image](https://user-images.githubusercontent.com/9133679/235912777-a9f45238-8f03-4f96-8b76-c1808041e45b.png)
