### ISSUE TITLE
Allow configuring SIGKILL timeout

### ISSUE THREAD

**Issue by Karankang007** [karma-runner/karma#2457] opened 2016-11-15 17:31 UTC
The SIGKILL timeout is currently hardocoded in launcher\process.js file. On our CI build server, the process exit takes longer than 2 seconds when running large number of tests, as the process exit waits for all Chrome child processes to be killed.

Is it possible to make this timeout configurable?

>    "gulp": "~3.9.1",
>    "karma": "~1.3.0",
>     "karma-chrome-launcher": "~2.0.0",
>     "karma-coverage": "~1.1.1",
>     "karma-html-reporter": "~0.2.7",
>     "karma-junit-reporter": "~1.1.0",
>     "karma-nested-reporter": "~0.1.4",
>     "karma-jasmine": "~1.0.2",
>     "karma-jasmine-runner2-reporter": "~0.3.5"

**Comment by vivganes** [comment] 2016-11-25 16:44
@Karankang007  This issue seems to be a duplicate of already reported issue: https://github.com/karma-runner/karma/issues/2447

Can you please take a look at it and close this issue if this is a duplicate? 

There is a possibility that I am wrong in my understanding.

**Comment by maksimr** [comment] 2016-11-25 18:21
Close as duplicate https://github.com/karma-runner/karma/issues/2447

**Closed by maksimr** 2016-11-25 18:21 UTC
